### ISSUE TITLE
老哥你这能用不

### ISSUE THREAD

**Issue by hage1527** [mo10/FuckCampushoy#1]

**Comment by mo10** [comment]
已实现扫描登陆，拉取辅导员问卷，自动回答问卷（简单问题）
需要修改的部分有：[Notify.cs](https://github.com/mo10/FuckCampushoy/blob/master/FuckCampushoy/Notify.cs#L44)  [Login.cs](https://github.com/mo10/FuckCampushoy/blob/master/FuckCampushoy/Login.cs#L70)内的url，填写成你们学校的url，具体可以使用fiddler抓到。
简单的问卷填写也在Notify.cs，建议配合fiddler分析。

目前不足的是cookie会失效，每次都需要重新扫码登陆

**Comment by mo10** [comment]
Cookie需要定时请求api来保活 我又写了个python flask版本，目前测试活了3天
